### ISSUE TITLE
Calling main from a function pointer fails with GCC 6

### ISSUE THREAD

**Issue by ChristianRinn** [prof7bit/bare_metal_stm32f401xe#3]
Hi,

I tried to compile and run the bare metal example which I [adopted to the Nucleo F411](https://github.com/ChristianRinn/bare_metal_stm32f411xe) with GCC 6.3.0 and landed in the default handler instead of main, while everything works perfectly fine with GCC 4.9.3. It simply crashes when calling` __main__();` .
Changing the call of the main function to a simple `main();` and marking the function with `__attribute__((noinline))` did the trick, keeping it non-inlined. Interestingly I only got it to compile as a release build (with -0s and -flto) because a `make DEBUG=1` leads to the following error.

`src/STM32F411XE/gcc_startup_system.c: In function 'Reset_Handler':
src/STM32F411XE/gcc_startup_system.c:197:20: error: cannot allocate stack for variable '__main__', naked function.
     int(* volatile __main__)(void) = main;
`

I wonder why the compiler does not complain for a release build but instead generates complete bogus, e.g. `ldr R3, [sp, #4]` which should point somewhere beyond the end of RAM (see screenshot below). The value of the `__main__` pointer also seems way off.

![screenshot_20170401](https://cloud.githubusercontent.com/assets/10540226/24581983/34f818d0-1726-11e7-9086-7c2a4c8bb498.png)

This is probably the same issue that lead to  https://github.com/prof7bit/bare_metal_stm32f401xe/issues/2 because he is also using Arch Linux and probably had GCC 6 installed.

Anyhow I do not really understand why one should worry about the compiler inling the main function at all. Can you give me a hint why I should avoid that?

**Comment by prof7bit** [comment]
> Anyhow I do not really understand why one should worry about the compiler inling the main function at all. Can you give me a hint why I should avoid that?

You are right, on the STM32 it would not matter.  But I have ported parts of this from one of my Kinetis Startup codes and on these Kinetis chips the startup and the SystemInit() is usually put into a different memory section (the otherwise unused 700 bytes hole between vectors and flash config bytes) than the rest of the code. The linker with -flto is not smart enough and would blindly try to inline even if there is not enough room and then abort with memory section overflowed error.

On STM32 there is no such need and it could all be inlined, it can safely be replaced with a simple function call to main()

I have currently lent out my Nucleo Board to a colleague, I will try to get it back this week and investigate what exactly happens with the new gcc 6 compiler.

**Comment by prof7bit** [comment]
I should not have declared the reset handler naked and still use local variables, I wonder why this worked at all and did not immediately crash with any compiler and any optimization setting.

Can you try what happens if you just remove the NAKED from the reset handler?

**Comment by ChristianRinn** [comment]
Thanks for the explanation of why it should not be inlined. Now that totally makes sense to me.

Removing the naked attribute did work indeed with the function pointer construct. If you want, you can have a look at the attached assembly listings (as .txt because .lst is too evil for Github).

As far as I understand it, GCC 4.9 happily ignores the "volatile" keyword for the function pointer and does not put it on the stack which could be seen as a feature as well as a bug (see naked_gcc4*). All other local variables are non-volatile and therefore put into registers anyway, so the "naked" attribute is no problem. This is also why everything works as expected if you use the "naked" attribute for the reset handler in combination with the "noinline" attribute for the main function and omit the function pointer to main (see naked_no-inline_gcc6*). 

naked_gcc6_-Os is the one that crashes. Now I understand why it crashes but not why the compiler complains when I use -Og but not with -Os.

The last listing is the one with the non-naked reset handler. It works as expected but throws away a few bytes of stack space for pushing the registers in the beginning of the reset handler (which is obviously not needed) but anyway it works.

[naked_gcc4-Og.txt](https://github.com/prof7bit/bare_metal_stm32f401xe/files/890828/naked_gcc4-Og.txt)
[naked_gcc4-Os.txt](https://github.com/prof7bit/bare_metal_stm32f401xe/files/890823/naked_gcc4-Os.txt)
[naked_gcc6-Os.txt](https://github.com/prof7bit/bare_metal_stm32f401xe/files/890827/naked_gcc6-Os.txt)
[naked_no-inline_gcc6-Og.txt](https://github.com/prof7bit/bare_metal_stm32f401xe/files/890825/naked_no-inline_gcc6-Og.txt)
[naked_no-inline_gcc6-Os.txt](https://github.com/prof7bit/bare_metal_stm32f401xe/files/890824/naked_no-inline_gcc6-Os.txt)
[non-naked_gcc6-Os.txt](https://github.com/prof7bit/bare_metal_stm32f401xe/files/890826/non-naked_gcc6-Os.txt)

**Comment by prof7bit** [comment]
>  Now I understand why it crashes but not why the compiler complains when I use -Og but not with -Os.

I believe it happens because with -Og it tries to put the `__main__` variable on the stack while in higher optimization levels it will just use another register.

But I think it is an error and undefined behavior anyways to attempt to use C code in naked functions and allow the optimizer to mess around with it. I have experimented a bit with this and it is possible to make the compiler inline a function that uses variables on the stack into a naked function without stack frame and then the compiler will not detect it and not complain about it!

My current solution now is a naked asm-only function that just calls three other functtions. Now the Reset_Handler does not contribute to stack usage anymore at all. And the code will not use undefined behavior anymore (local variables, possible inlining of non-naked other functions).

The real solution would be when arm-gcc would implement the OS_main function attribute (which it unfortunately does not), then it could be safely written in C and still avoid pushing all these registers (also in main() itself)
